import 'package:flutter/material.dart';

abstract class IconPack{
  static IconData getServiceIcon(String? iconName) {
    switch (iconName?.toLowerCase()) {
      case 'home':
        return Icons.home;
      case 'home_rounded':
        return Icons.home_rounded;
      case 'home_outlined':
        return Icons.home_outlined;
      case 'shopping_cart':
      case 'cart':
      case 'shopping':
        return Icons.shopping_cart;
      case 'shopping_bag':
      case 'bag':
        return Icons.shopping_bag;
      case 'delivery':
      case 'shipping':
      case 'local_shipping':
        return Icons.local_shipping;
      case 'agriculture':
      case 'farming':
        return Icons.agriculture;
      case 'repair':
      case 'build':
        return Icons.build;
      case 'construction':
        return Icons.construction;
      case 'handyman':
        return Icons.handyman;
      case 'cleaning_services':
      case 'cleaning':
        return Icons.cleaning_services;
      case 'plumbing':
        return Icons.plumbing;
      case 'electrical_services':
      case 'electrical':
        return Icons.electrical_services;
      case 'ac_unit':
      case 'air_conditioning':
        return Icons.ac_unit;
      case 'restaurant':
      case 'food':
        return Icons.restaurant;
      case 'local_cafe':
      case 'cafe':
      case 'coffee':
        return Icons.local_cafe;
      case 'local_pizza':
      case 'pizza':
        return Icons.local_pizza;
      case 'local_hospital':
      case 'hospital':
        return Icons.local_hospital;
      case 'medical_services':
      case 'medical':
        return Icons.medical_services;
      case 'local_pharmacy':
      case 'pharmacy':
        return Icons.local_pharmacy;
      case 'school':
      case 'education':
        return Icons.school;
      case 'book':
        return Icons.book;
      case 'library_books':
      case 'library':
        return Icons.library_books;
      case 'fitness_center':
      case 'gym':
        return Icons.fitness_center;
      case 'sports':
        return Icons.sports;
      case 'spa':
        return Icons.spa;
      case 'local_laundry_service':
      case 'laundry':
        return Icons.local_laundry_service;
      case 'dry_cleaning':
        return Icons.dry_cleaning;
      case 'car_repair':
      case 'garage':
        return Icons.car_repair;
      case 'directions_car':
      case 'car':
        return Icons.directions_car;
      case 'two_wheeler':
      case 'motorcycle':
        return Icons.two_wheeler;
      case 'local_taxi':
      case 'taxi':
        return Icons.local_taxi;
      case 'airport_shuttle':
      case 'shuttle':
        return Icons.airport_shuttle;
      case 'flight':
      case 'airplane':
        return Icons.flight;
      case 'hotel':
      case 'accommodation':
        return Icons.hotel;
      case 'apartment':
        return Icons.apartment;
      case 'house':
        return Icons.house;
      case 'business':
      case 'office':
        return Icons.business;
      case 'store':
      case 'shop':
        return Icons.store;
      case 'local_grocery_store':
      case 'grocery':
        return Icons.local_grocery_store;
      case 'restaurant_menu':
      case 'menu':
        return Icons.restaurant_menu;
      case 'local_bar':
      case 'bar':
        return Icons.local_bar;
      case 'local_florist':
      case 'flowers':
        return Icons.local_florist;
      case 'pets':
      case 'pet':
        return Icons.pets;
      case 'child_care':
      case 'daycare':
        return Icons.child_care;
      case 'elderly':
      case 'elderly_care':
        return Icons.elderly;
      case 'accessibility':
        return Icons.accessibility;
      case 'campaign':
      case 'marketing':
        return Icons.campaign;
      case 'print':
      case 'printing':
        return Icons.print;
      case 'computer':
      case 'it':
        return Icons.computer;
      case 'phone':
      case 'mobile':
        return Icons.phone;
      case 'camera':
      case 'photography':
        return Icons.camera;
      case 'videocam':
      case 'video':
        return Icons.videocam;
      case 'music_note':
      case 'music':
        return Icons.music_note;
      case 'palette':
      case 'art':
        return Icons.palette;
      case 'brush':
      case 'painting':
        return Icons.brush;
      case 'content_cut':
      case 'haircut':
        return Icons.content_cut;
      case 'face':
      case 'beauty':
        return Icons.face;
      case 'celebration':
      case 'event':
        return Icons.celebration;
      case 'cake':
      case 'bakery':
        return Icons.cake;
      case 'local_offer':
      case 'offer':
      case 'discount':
        return Icons.local_offer;
      case 'attach_money':
      case 'money':
      case 'finance':
        return Icons.attach_money;
      case 'account_balance':
      case 'bank':
        return Icons.account_balance;
      case 'credit_card':
        return Icons.credit_card;
      case 'wallet':
      case 'payment':
        return Icons.wallet;
      case 'security':
      case 'secure':
        return Icons.security;
      case 'vpn_key':
      case 'key':
        return Icons.vpn_key;
      case 'lock':
        return Icons.lock;
      case 'verified':
      case 'verified_user':
        return Icons.verified_user;
      case 'gavel':
      case 'legal':
      case 'law':
        return Icons.gavel;
      case 'description':
      case 'document':
        return Icons.description;
      case 'folder':
        return Icons.folder;
      case 'cloud':
      case 'cloud_storage':
        return Icons.cloud;
      case 'backup':
        return Icons.backup;
      case 'settings':
        return Icons.settings;
      case 'support':
      case 'help':
        return Icons.support;
      case 'chat':
      case 'message':
        return Icons.chat;
      case 'email':
      case 'mail':
        return Icons.email;
      case 'call':
        return Icons.call;
      case 'notifications':
      case 'notification':
        return Icons.notifications;
      case 'schedule':
      case 'time':
        return Icons.schedule;
      case 'calendar_today':
      case 'calendar':
        return Icons.calendar_today;
      case 'today':
        return Icons.today;
      case 'location_on':
      case 'location':
        return Icons.location_on;
      case 'map':
        return Icons.map;
      case 'directions':
        return Icons.directions;
      case 'near_me':
      case 'nearby':
        return Icons.near_me;
      case 'star':
      case 'favorite':
        return Icons.star;
      case 'thumb_up':
      case 'like':
        return Icons.thumb_up;
      case 'share':
        return Icons.share;
      case 'bookmark':
        return Icons.bookmark;
      case 'flag':
        return Icons.flag;
      case 'report':
        return Icons.report;
      case 'warning':
        return Icons.warning;
      case 'info':
        return Icons.info;
      case 'check_circle':
      case 'success':
        return Icons.check_circle;
      case 'cancel':
      case 'close':
        return Icons.cancel;
      case 'add':
      case 'plus':
        return Icons.add;
      case 'remove':
      case 'minus':
        return Icons.remove;
      case 'edit':
        return Icons.edit;
      case 'delete':
        return Icons.delete;
      case 'search':
        return Icons.search;
      case 'filter_list':
      case 'filter':
        return Icons.filter_list;
      case 'sort':
        return Icons.sort;
      case 'visibility':
      case 'view':
        return Icons.visibility;
      case 'download':
        return Icons.download;
      case 'upload':
        return Icons.upload;
      case 'refresh':
        return Icons.refresh;
      case 'sync':
        return Icons.sync;
      case 'dashboard':
        return Icons.dashboard;
      case 'analytics':
      case 'insights':
        return Icons.analytics;
      case 'pie_chart':
      case 'chart':
        return Icons.pie_chart;
      case 'show_chart':
      case 'graph':
        return Icons.show_chart;
      case 'trending_up':
      case 'trending':
        return Icons.trending_up;
      case 'inventory':
      case 'stock':
        return Icons.inventory;
      case 'local_shipping_outlined':
        return Icons.local_shipping_outlined;
      case 'delivery_dining':
        return Icons.delivery_dining;
      case 'fastfood':
        return Icons.fastfood;
      case 'ramen_dining':
      case 'ramen':
        return Icons.ramen_dining;
      case 'rice_bowl':
        return Icons.rice_bowl;
      case 'brunch_dining':
      case 'brunch':
        return Icons.brunch_dining;
      case 'dinner_dining':
      case 'dinner':
        return Icons.dinner_dining;
      case 'lunch_dining':
      case 'lunch':
        return Icons.lunch_dining;
      case 'breakfast_dining':
      case 'breakfast':
        return Icons.breakfast_dining;
      case 'liquor':
      case 'alcohol':
        return Icons.liquor;
      case 'wine_bar':
      case 'wine':
        return Icons.wine_bar;
      case 'nightlife':
      case 'night':
        return Icons.nightlife;
      case 'sports_bar':
        return Icons.sports_bar;
      case 'eco':
      case 'green':
      case 'environmental':
        return Icons.eco;
      case 'recycling':
      case 'recycle':
        return Icons.recycling;
      case 'energy_savings_leaf':
      case 'energy':
        return Icons.energy_savings_leaf;
      case 'water_drop':
      case 'water':
        return Icons.water_drop;
      case 'wb_sunny':
      case 'solar':
      case 'sun':
        return Icons.wb_sunny;
      case 'bolt':
      case 'electricity':
        return Icons.bolt;
      case 'light':
      case 'lightbulb':
        return Icons.lightbulb;
      case 'power':
        return Icons.power;
      case 'hvac':
        return Icons.hvac;
      case 'heat_pump':
        return Icons.heat_pump;
      case 'thermostat':
        return Icons.thermostat;
      case 'device_thermostat':
        return Icons.device_thermostat;
      case 'roofing':
      case 'roof':
        return Icons.roofing;
      case 'window':
        return Icons.window;
      case 'door_sliding':
      case 'door':
        return Icons.door_sliding;
      case 'fence':
        return Icons.fence;
      case 'deck':
        return Icons.deck;
      case 'foundation':
        return Icons.foundation;
      case 'stairs':
        return Icons.stairs;
      case 'elevator':
        return Icons.elevator;
      case 'escalator':
        return Icons.escalator;
      case 'bathtub':
      case 'bath':
        return Icons.bathtub;
      case 'shower':
        return Icons.shower;
      case 'hot_tub':
        return Icons.hot_tub;
      case 'pool':
      case 'swimming':
        return Icons.pool;
      case 'grass':
      case 'lawn':
        return Icons.grass;
      case 'yard':
        return Icons.yard;
      case 'forest':
      case 'tree':
        return Icons.forest;
      case 'park':
        return Icons.park;
      case 'landscape':
        return Icons.landscape;
      case 'nature':
      case 'nature_people':
        return Icons.nature_people;
      case 'home_repair_service':
        return Icons.home_repair_service;
      case 'home_repair_service_rounded':
        return Icons.home_repair_service_rounded;
      default:
        return Icons.home_repair_service_rounded;
    }
  }
}